server:
  port: 9001

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9001
      authorizationserver:
        issuer: http://127.0.0.1:9001
        client:
          task-manager-client:
            registration:
              client-id: task-manager-client
              client-secret: "{noop}secret"
              client-name: Task Manager Client
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
              redirect-uris:
                - http://127.0.0.1:8080/login/oauth2/code/task-manager-client-oidc
                - http://127.0.0.1:8080/authorized
              scopes:
                - openid
                - task-manager.read

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
