server:
  port: 9001

spring:
  security:
    oauth2:
      authorizationserver:
        issuer: http://auth-server:9001
        client:
          task-manager-client:
            registration:
              client-id: task-manager-client
              client-secret: "{noop}secret-task-manager"
              client-name: Task Manager Client
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
              redirect-uris:
                - http://127.0.0.1:8080/login/oauth2/code/task-manager-client-oidc
                - http://127.0.0.1:8080/authorized
              scopes:
                - openid
                - task-manager
          accounting-client:
            registration:
              client-id: accounting-client
              client-secret: "{noop}secret-accounting"
              client-name: Accounting Client
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
              redirect-uris:
                - http://127.0.0.1:8080/login/oauth2/code/accounting-client-oidc
                - http://127.0.0.1:8080/authorized
              scopes:
                - openid
                - accounting
          analytics-client:
            registration:
              client-id: analytics-client
              client-secret: "{noop}secret-analytics"
              client-name: Analytics Client
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
              redirect-uris:
                - http://127.0.0.1:8080/login/oauth2/code/analytics-client-oidc
                - http://127.0.0.1:8080/authorized
              scopes:
                - openid
                - analytics

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
